[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
prague = true
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solady/=lib/solady/src/",
  "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
solc = "bin/solc"

[fmt]
bracket_spacing = true
